name: Tony Bartish
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8893782799132168
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#1371bf'
    - '#a5b5c3'
    - '#d73986'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
